name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: copy git repository
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/Server
            source ~/.bashrc
            git pull origin main

      - name: build & run the code
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/Server
            chmod +x ./gradlew
            ./gradlew clean build
            pkill -f spring-0.0.1-SNAPSHOT.jar || true
            nohup java -jar build/libs/spring-0.0.1-SNAPSHOT.jar > /home/ubuntu/app.log 2>&1 &
            pgrep -f spring-0.0.1-SNAPSHOT.jar && echo "Application is running"
