name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: copy git repository
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/Server
            git pull origin main
            cd ~
            source .bashrc

      - name: build & run the code
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/Server
            chmod +x ./gradlew
            ./gradlew clean build
            pkill -f spring-0.0.1-SNAPSHOT.jar || true
            cd build/libs/
            nohup java -jar spring-0.0.1-SNAPSHOT.jar &
